### ISSUE TITLE
Modify endpoints messages

### ISSUE THREAD

**Issue by Alberthor47** [hyfi06/platzi-master-end-game-backend#99]
Similar to the issue opened by Luis Flores for the user messages, I need a revision of API returning messages in the orders and results endpoints.

Example: When a patient has no related orders the message that the API responds is "test not found" when it does not represent the real error, it can be changed with a similar but more descriptive message like "Tests not found for this user"

After the review, if there's a need to make changes like the example mentioned before I put under your consideration the message just asking to be descriptive so we can render it on the frontend.

**Comment by ealexisaraujo** [comment]
Can we close this issue?

**Comment by Alberthor47** [comment]
I prefer to wait until we test al the ussers flow
